GET http://localhost:3000/api/notes

###
GET http://localhost:3000/api/notes/64d7ae299e254a2d1b6adb83

###

POST http://localhost:3000/api/notes
Content-Type: application/json

{
    "title": "test2",
    "content": "second"
}

####
DELETE http://localhost:3000/api/notes/64d7ae299e254a2d1b6adb83
